#!/usr/bin/env node
/* Apollo Films — turn the prepped material into the page's data file.

       node tools/backstage-data.mjs        # writes assets/js/backstage.js

   Run after tools/backstage-prep.mjs.

   ONE WALL, NOT EIGHT GALLERIES. The prep pass groups the masters by the
   production they came from, because that is what their filenames say and it
   is how the material has to be FILED. The archive does not show them that
   way. It is one mixed wall of behind-the-scenes work with every production
   on it at once, and a production's name is a fact about a photograph rather
   than a place it lives — Mirage turns up in five different corners of the
   wall, and Shopigo's single frame is simply part of the composition instead
   of a lonely gallery of one.

   So this pass FLATTENS what prep filed. It emits one pool of frames and one
   pool of cuts, each carrying the production it belongs to, and hands the
   composition to assets/js/archive.js — which lays the wall out and
   deliberately keeps frames of the same production apart. */

import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const WEB = path.join(ROOT, 'assets', 'backstage', 'web');
const OUT = path.join(ROOT, 'assets', 'js', 'backstage.js');

const manifest = JSON.parse(fs.readFileSync(path.join(WEB, 'manifest.json'), 'utf8'));

console.log('— backstage data —\n');

const L = [];
const p = (s) => L.push(s);

p(`/* Apollo Films — behind the scenes.`);
p(`   Generated by tools/backstage-data.mjs. Safe to hand-edit: the page`);
p(`   reads this file directly and there is no build step between them.`);
p(``);
p(`   ONE WALL. Every frame and both cuts are in one flat pool here, each`);
p(`   carrying the production it came from. \`of\` is a LABEL and not a`);
p(`   location: the archive is a single mixed wall, and archive.js deals`);
p(`   these out across it deliberately keeping same-production frames apart,`);
p(`   so Mirage turns up in several corners rather than in a Mirage corner.`);
p(``);
p(`   Every frame ships at two sizes: a 640px -thumb for the wall and a`);
p(`   1600px -view for the opened frame. A frame with a \`tall\` block was`);
p(`   delivered cropped twice — the wide crop is the default and the tall one`);
p(`   is what a phone gets. */`);
p(``);
p(`const BS = 'assets/backstage/web/';`);
p(``);
p(`window.APOLLO_BACKSTAGE = {`);
p(``);
p(`  /* Title and catalogue slug per production, for the one label the wall`);
p(`     carries: the name of whatever the cursor is over. */`);
p(`  films: {`);
manifest.clusters.forEach((c, i) => {
  const tail = i === manifest.clusters.length - 1 ? '' : ',';
  p(`    '${c.id}': { title: ${JSON.stringify(c.title)}, film: ${c.film ? `'${c.film}'` : 'null'} }${tail}`);
});
p(`  },`);
p(``);

const cuts = manifest.clusters.filter((c) => c.cut);
p(`  /* The cuts. The largest things on the wall and the only ones that move`);
p(`     on their own. Neither is attached until the camera is near it. */`);
p(`  cuts: [`);
cuts.forEach((c, i) => {
  const cut = c.cut;
  p(`    {`);
  p(`      of: '${c.id}',`);
  p(`      src: BS + '${cut.slug}.mp4',`);
  p(`      poster: BS + '${cut.slug}-poster.webp',`);
  p(`      ratio: ${cut.w} / ${cut.h},`);
  p(`      seconds: ${cut.seconds}${cut.wide ? ',' : ''}`);
  if (cut.wide) {
    p(`      /* The same edit at 16:9, for a room with the width to take it. */`);
    p(`      wide: {`);
    p(`        src: BS + '${cut.slug}-desktop.mp4',`);
    p(`        poster: BS + '${cut.slug}-desktop-poster.webp',`);
    p(`        ratio: ${cut.wide.w} / ${cut.wide.h}`);
    p(`      }`);
  }
  p(`    }${i === cuts.length - 1 ? '' : ','}`);
});
p(`  ],`);
p(``);

const shots = [];
for (const c of manifest.clusters) for (const sh of c.shots) shots.push({ ...sh, of: c.id });
p(`  /* Every frame on the wall, filed by production. The ORDER here is the`);
p(`     order they were delivered in and nothing more — archive.js re-deals`);
p(`     them before it places any of them. */`);
p(`  shots: [`);
shots.forEach((sh, i) => {
  const tail = i === shots.length - 1 ? '' : ',';
  if (sh.tall) {
    p(`    { s: '${sh.slug}', of: '${sh.of}', w: ${sh.w}, h: ${sh.h},`);
    p(`      tall: { w: ${sh.tall.w}, h: ${sh.tall.h} } }${tail}`);
  } else {
    p(`    { s: '${sh.slug}', of: '${sh.of}', w: ${sh.w}, h: ${sh.h} }${tail}`);
  }
});
p(`  ]`);
p(`};`);
p(``);

fs.writeFileSync(OUT, L.join('\n'));

for (const c of manifest.clusters) {
  console.log(`  ${c.id.padEnd(14)} ${String(c.shots.length).padStart(3)} frames${c.cut ? '  + cut' : ''}`);
}
console.log(`\n  ${shots.length} frames and ${cuts.length} cuts, onto one wall`);
console.log(`\nwrote assets/js/backstage.js`);
