#!/usr/bin/env node
/* Apollo Films — turn the prepped frames into the page's data file.

       node tools/backstage-data.mjs        # writes assets/js/backstage.js

   Run after tools/backstage-prep.mjs. Reads the derivatives in
   assets/backstage/web/, works out what is actually in them, and writes
   assets/js/backstage.js the way films.js is written: one hand-readable
   data file the page reads, with no build step between it and the browser.

   Two things the prep pass could not know, both learned by looking at the
   material rather than at the filenames:

   1. The date in a WhatsApp filename is the DELIVERY date, not the shoot.
      The 2026-05-24 batch is the 2026-04-08 batch sent a second time, and
      WhatsApp re-compresses on every send, so the bytes differ and an md5
      pass keeps both copies. Frames are compared here on an 8x8 average
      hash instead, which sees through the recompression.

   2. The batches are not one kind of thing. 2026-04-08 is photography from
      the floor — crew, camera, talent. 2026-05-25 is finished key art:
      Mirage, La Casa De Raisa Vanessa, Il Leone, Summer Lovers. Those are
      worth showing and worth labelling honestly, so they are their own
      strip rather than being passed off as behind-the-scenes.

   Set titles are the one thing left to a human. They are declared just
   below; edit them there and re-run, or edit the generated file directly. */

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const WEB = path.join(ROOT, 'assets', 'backstage', 'web');
const OUT = path.join(ROOT, 'assets', 'js', 'backstage.js');

/* Which delivery batch is which kind of material, and what each strip is
   called on the page. Add a batch here when new material arrives. */
const STRIPS = [
  {
    id: 'floor',
    dir: 'assets/backstage/web/',
    title: 'On the floor',
    note: 'Crew, camera and cast between takes.',
    batches: ['2026-04-08', '2026-05-24']
  },
  {
    /* Lifted into its own directory and renamed after the films by
       tools/posters-split.mjs — see assets/posters/posters.md. Re-running
       this generator rebuilds the strip from the raw batch names, so run
       posters-split.mjs after it to restore the poster names. */
    id: 'keyart',
    dir: 'assets/posters/',
    title: 'Key art',
    note: 'Posters cut for the films.',
    batches: ['2026-05-25']
  }
];

/* Frames to leave out, with the reason. `-22` is a phone screenshot of the
   site open inside Instagram's in-app browser — status bar, address bar and
   all — rather than a photograph. */
const EXCLUDE = new Set(['2026-05-25-22']);

function aHash(file) {
  const buf = execFileSync('ffmpeg', [
    '-v', 'error', '-i', file, '-vf', 'scale=8:8,format=gray', '-f', 'rawvideo', '-'
  ], { maxBuffer: 1 << 20 });
  const px = [...buf.subarray(0, 64)];
  const avg = px.reduce((a, b) => a + b, 0) / 64;
  let bits = 0n;
  px.forEach((v, i) => { if (v > avg) bits |= (1n << BigInt(i)); });
  return bits;
}

const hamming = (a, b) => {
  let x = a ^ b, c = 0;
  while (x) { c += Number(x & 1n); x >>= 1n; }
  return c;
};

const manifest = JSON.parse(fs.readFileSync(path.join(WEB, 'manifest.json'), 'utf8'));
const byBatch = new Map(manifest.sets.map((s) => [s.shoot, s.shots]));

console.log('— backstage data —\n');

const strips = [];
const kept = [];   /* running list of hashes, so a later batch cannot repeat an earlier one */

for (const strip of STRIPS) {
  const shots = [];
  for (const batch of strip.batches) {
    for (const shot of byBatch.get(batch) ?? []) {
      if (EXCLUDE.has(shot.slug)) continue;
      const h = aHash(path.join(WEB, `${shot.slug}-thumb.webp`));
      /* <= 4 bits apart is the same photograph through a second round of
         WhatsApp compression; anything looser starts eating real frames. */
      if (kept.some((k) => hamming(k, h) <= 4)) continue;
      kept.push(h);
      shots.push({ slug: shot.slug, w: shot.w, h: shot.h });
    }
  }
  strips.push({ ...strip, shots });
  console.log(`  ${strip.id.padEnd(7)} ${String(shots.length).padStart(3)} frames  (${strip.title})`);
}

const dropped = manifest.sets.reduce((n, s) => n + s.shots.length, 0)
  - strips.reduce((n, s) => n + s.shots.length, 0);
console.log(`\n  ${dropped} dropped as repeats or non-photographs`);

/* ---- emit ---- */

const lines = [];
lines.push(`/* Apollo Films — behind the scenes.`);
lines.push(`   Generated by tools/backstage-data.mjs. Safe to hand-edit: the page`);
lines.push(`   reads this file directly and there is no build step between them.`);
lines.push(`   Re-running the generator overwrites it, so move a hand edit into`);
lines.push(`   STRIPS at the top of that script if you want it to survive.`);
lines.push(``);
lines.push(`   Paths are relative to the page. Every frame ships in two sizes: a`);
lines.push(`   640px -thumb for the strip and a 1600px -view for the lightbox, so`);
lines.push(`   a page of eighty frames costs eighty thumbnails, not eighty photos. */`);
lines.push(``);
lines.push(`const BS = 'assets/backstage/web/';`);
lines.push(``);
lines.push(`window.APOLLO_BACKSTAGE = {`);
lines.push(``);
lines.push(`  /* The two cuts, both 9:16 with sound — they were made for a phone.`);
lines.push(`     Neither is attached until it is asked for; see app.js. */`);
lines.push(`  films: [`);
for (const f of manifest.films) {
  lines.push(`    {`);
  lines.push(`      slug: '${f.slug}',`);
  lines.push(`      title: ${JSON.stringify(f.title)},`);
  lines.push(`      seconds: ${f.seconds},`);
  lines.push(`      src: BS + '${f.slug}.mp4',`);
  lines.push(`      poster: BS + '${f.slug}-poster.webp'`);
  lines.push(`    }${f === manifest.films.at(-1) ? '' : ','}`);
}
lines.push(`  ],`);
lines.push(``);
lines.push(`  strips: [`);
for (const s of strips) {
  lines.push(`    {`);
  lines.push(`      id: '${s.id}',`);
  lines.push(`      dir: '${s.dir}',`);
  lines.push(`      title: ${JSON.stringify(s.title)},`);
  lines.push(`      note: ${JSON.stringify(s.note)},`);
  lines.push(`      shots: [`);
  for (const sh of s.shots) {
    lines.push(`        { s: '${sh.slug}', w: ${sh.w}, h: ${sh.h} },`);
  }
  lines[lines.length - 1] = lines.at(-1).replace(/,$/, '');
  lines.push(`      ]`);
  lines.push(`    }${s === strips.at(-1) ? '' : ','}`);
}
lines.push(`  ]`);
lines.push(`};`);
lines.push(``);

fs.writeFileSync(OUT, lines.join('\n'));
console.log(`\nwrote assets/js/backstage.js`);
